dataset_path: YOUR_PATH_TO/VIR-Bench
dataset_kwargs:
  cache_dir: YOUR_PATH_TO/VIR-Bench
  video: True
  local_files_only: True
task: virbench_edge_prediction
test_split: test
doc_to_visual: !function utils.virbench_doc_to_visual
doc_to_text: !function utils.virbench_doc_to_text
doc_to_target: !function utils.virbench_doc_to_target
generation_kwargs:
  max_new_tokens: 4096
  temperature: 0
  do_sample: False
process_results: !function utils.edge_prediction_process_results
metric_list:
  - metric: virbench_scores
    aggregation: !function utils.edge_prediction_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    task: edge_prediction
    language: en
    pre_prompt: ""
    post_prompt: "Only return the JSON object. Do not include any explanation, comments, or additional text in the output."
  